spring.application.name=insight-service
server.port=8085

usage.service.url = http://localhost:8083/api/v1/usage

spring.ai.ollama.chat.options.model=llama3.2:latest
spring.ai.ollama.init.pull-model-strategy=never

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

