spring.application.name=api-gateway
server.port=8080

# Resilience4j Circuit Breaker configuration
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.deviceServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.deviceServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.deviceServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.deviceServiceCircuitBreaker.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.ingestionServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ingestionServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ingestionServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ingestionServiceCircuitBreaker.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.usageServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.usageServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.usageServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.usageServiceCircuitBreaker.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.alertServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.alertServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.alertServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.alertServiceCircuitBreaker.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.insightServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.insightServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.insightServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.insightServiceCircuitBreaker.waitDurationInOpenState=5s

# Actuator & Prometheus
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,prometheus
management.metrics.tags.application=${spring.application.name}

# Keycloak
keycloak.auth.jwk-set-uri=http://localhost:8091/realms/het-security-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/het-security-realm

# Security
security.excluded.urls=/actuator/**, /swagger-ui.html, /swagger-ui/**, /docs/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/docs/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Device Service
springdoc.swagger-ui.urls[1].url=/docs/device-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Ingestion Service
springdoc.swagger-ui.urls[2].url=/docs/ingestion-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Usage Service
springdoc.swagger-ui.urls[3].url=/docs/usage-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Alert Service
springdoc.swagger-ui.urls[4].url=/docs/alert-service/v3/api-docs
springdoc.swagger-ui.urls[5].name=Insight Service
springdoc.swagger-ui.urls[5].url=/docs/insight-service/v3/api-docs


